#!/usr/bin/env bash
# vim: set ts=4 sw=4 et:

if ! [[ -v RTASKDIR ]] ; then
    if ! [[ -v XDG_DATA_HOME ]] ; then
        XDG_DATA_HOME=$HOME/.local/share
    fi
    RTASKDIR=$XDG_DATA_HOME/tasks
fi

if ! [[ -d $RTASKDIR ]] ; then
  mkdir -p $RTASKDIR
fi

p=$HOME/.local/lib
case $1 in 
    add)
        shift 1 
        bash $p/rtask-add "$@"
        ;;
    list)
        shift 1 
        bash $p/rtask-list "$@"
        ;;
    comment)
        shift 1 
        bash $p/rtask-comment "$@"
        ;;
    *)
        echo "no"
        exit 1
        ;;
esac    


