#!/usr/bin/env bash
# vim: set ts=4 sw=4 et:
echo $BASH_VERSION

source rtask-util
RTASKDIR=$(gettasksdir)
pushd $RTASKDIR >/dev/null

if echo $1 | grep -q -E "^\d+(\.\d+)*$" ; then
       taskid=$1
       shift 1
fi
path=$(newtaskpath $taskid)
# echo creating path $path
# echo creating task at $path/task
mkdir -p $path
if [[ -z $* ]] ; then 
    ${EDITOR:=vim} $path/task
else
    echo "$*" > ${path}/task
fi

