#!/usr/bin/env bash
# vim: set ts=4 sw=4 et:
echo $BASH_VERSION


if ! [[ -v RTASKDIR ]] ; then 
    if ! [[ -v XDG_DATA_HOME ]] ; then 
        XDG_DATA_HOME=$HOME/.local/share
    fi
    RTASKDIR=$XDG_DATA_HOME/tasks
fi

if ! [[ -d $RTASKDIR ]] ; then 
  mkdir -p $RTASKDIR
fi

echo $RTASKDIR
pushd $RTASKDIR >/dev/null

# get new taskid

if echo $1 | grep -q -E "^\d+(\.\d+)*$" ; then 
	taskid=$1
   	shift 1
    if echo $taskid | grep -q "\." ; then
       	path=""
       	pathsep="/tasks/"
       	array=${taskid//./ }  
       	for e in $(echo $array) ; do 
      		path=$(echo $path$e$pathsep)
       	done 
        if ! [[ -d ${path:0:length-6} ]] ; then 
            echo TaskID does not exist
            exit 1
        fi
        lastid=$(ls $path 2>/dev/null | grep "[0-9]*" | wc -l)
	    taskid=$(($lastid+1))
        path=$path$taskid
   	else
        if ! [[ -d $taskid ]] ; then
            echo TaskID does not exist
            exit 1
        fi
       	path=$taskid/tasks
        lastid=$(ls $path 2>/dev/null | grep "[0-9]*" | wc -l)
	    taskid=$(($lastid+1))
        path=$path/$taskid
   	fi
else 
	lastid=$(find * -maxdepth 0 -type d -regex "[0-9]*" | wc -l)
	taskid=$(($lastid+1))
	path=$taskid
fi	

echo creating path $path
echo creating task at $path/task
mkdir -p $path

if [[ -z $* ]] ; then 
    ${EDITOR:=vim} $path/task
else
    echo $* > $path/task
fi

