#!/usr/bin/env bash
# vim: set ts=4 sw=4 et:

source rtask-util
RTASKSDIR=$(gettasksdir)
pushd $RTASKDIR >/dev/null


if echo $1 | grep -q -E "^\d+(\.\d+)*$" ; then 
	taskid=$1
else 
    echo "please add taskid to comment on"
    exit 1
fi
shift 1 
path=$(newcommentpath $taskid)
echo creating path $(dirname $path)
echo creating comment at $path
mkdir -p $(dirname $path)
if [[ -z $* ]] ; then 
    ${EDITOR:=vim} $path
else
    echo $* > $path
fi
