#!/usr/bin/env bash
# vim: set ts=4 sw=4 et:

usage() {
    cat <<'EOF'

    USAGE: rtask <action> <taskid> <text>
    if not given any arguments, rtask prints out a list of tasks
    
    Available Actions
    
    * add: rtask add <taskid> <text>.
      * if taskid is not specified it opens a new task
      * If taskid is specified, it opens a sub-task  
      * If text is not specified, it opens an editor
    * list: rtask list <taskid>
      * if taskid is specified, it prints out all the 
        detailsx for that task
    * complete: rtask complete taskid
      * marks a task as complete and removes it from 
        the list view
    * edit: rtask edit taskid 
      * opens $EDITOR for that task
    * comment: rtask comment taskid
      * adds a comment to a task
    * priority: rtask priority <taskid> <value>  
      * sets the priority of a task to make it appear
        higher or lower in the list
      * default is 0, negative numbers are lower
        priority and positive numbers are higher
    * move: rtask move <taskid> <taskid>
      * move a subtask to a different parent task
EOF
exit 1   
}

tasksdir=$(gettasksdir)
[[ -d $tasksdir ]] || mkdir -p $tasksdir 
pushd $tasksdir > /dev/null 

[[ -z $1 ]] && action="list" || action=$1
shift 1
### if the next argument matches a taskid...
if echo $1 | grep -q -E "^\d+(\.\d+)*$" ; then
       taskid=$1
       shift 1
fi

if ! [[ $action = "add" || $action = "list" ]] ; then 
    if  ! [[ -v taskid ]]  ; then 
        usage
    fi
fi

main() {
    case $action in 
        edit)
            edit 
            ;;
        complete) 
            finish 
            ;;
        move)
            move $taskid $text
            ;;
        add)
            text="$*"
            add "$text"
            ;;
        list) #
            if [[ -v taskid ]] ; then 
                details $taskid 
            else
                list 
            fi
            ;;
        priority) #
            setpriority $taskid $text 
            ;;
        comment) # 
            text="$*"
            comment "$text"
            ;;
        *)
            usage
            exit 1
            ;;
    esac    
}

###########################################################
#
# ACTIONS
#
###########################################################



finish() {
    touch $(taskpath $taskid)/complete
}

move() {
    mv $(taskpath $1) $(newtaskpath $2)
    echo $(taskpath $1)
    echo $(newtaskpath $2) 
}
details() {
    path=$(taskpath $taskid)
    if [[ -e $path/complete ]] ; then echo -n "DONE: " ; fi
    if [[ -e $path/task ]] ; then cat $path/task ; fi
    if [[ -d $path/comments ]] ; then cat $path/comments/* ; fi
    if [[ -e $path/priority ]] ; then echo -n "P " ; cat $path/priority ; else echo "P 0" ; fi
}

list() {
    tasklist=$(for f in $(find . -name task) ; do td=$(dirname $f) ; if [[ -e $td/priority ]] ; then p=$(cat $td/priority) ; else p=0 ; fi ; echo "$p $f" ; done | sort -k1,1nr -k2,2n | cut -f 2- -d ' ')
    # tasklist=$(find . -name task | sort -n)
    for f in $tasklist ; do
        taskdir="$(dirname $f)"
        if [[ -e $taskdir/complete ]] ; then
            continue
        fi
        taskfile=$(taskid $f)
        comments=$(getcommentcount $f)
        echo -n "$taskfile: "
        if [[ $comments -ne 0 ]] ; then
            echo -n "($comments) "
        fi
	    cat $f
    done
}

add() {
    path=$(newtaskpath $taskid)
    mkdir -p $path
    [[ -z $text ]] && ${EDITOR:=vim} $path/task || echo "$text" > ${path}/task
}

comment() {
    path=$(newcommentpath $taskid)
    mkdir -p $(dirname $path)
    [[ -z $* ]] && ${EDITOR:=vim} $path || echo $* > $path
}

edit() {
    ${EDITOR:=vim} $(taskpath $taskid)/task
}

setpriority() {
    path=$(taskpath $taskid)/priority
    echo $2 > $path
}

###########################################################
#
# Utitlities
#
###########################################################


gettasksdir() {
    if ! [[ -v RTASKDIR ]] ; then
        if ! [[ -v XDG_DATA_HOME ]] ; then
            XDG_DATA_HOME=$HOME/.local/share
        fi
        RTASKDIR=$XDG_DATA_HOME/tasks
    fi
    echo $RTASKDIR
}

taskid() {
    local path=$1
    if echo $path | grep -q tasks ; then 
        id=$(echo $path | sed -e 's!^\./!!g' | sed -e 's!/tasks/!.!g' | sed -e 's!/task$!!')
    else
        id=$(echo $path | sed -e  's!^\./!!g' | sed -e 's!/!!g' | sed -e 's!task$!!')
    fi
    echo $id
}

taskpath()  {
    if [[ -z $1 ]] ; then 
        path="."
    else 
        local id=$1
        if echo $id | grep -q "\." ; then
            path=""
            pathsep="/tasks/"
            array=${id//./ }  
            for e in $(echo $array) ; do 
                path=$(echo $path$e$pathsep)
            done 
            # take the last pathsep off
            path=$(echo $path | sed -e 's!/tasks/$!!')
        else 
            path=$id
        fi
    fi
    echo $path
}

getcommentcount() {
    comment_str=""
    taskdir="$(dirname $1)"
    comment_count=$(ls $taskdir/comments/ 2>/dev/null | wc -l)
    comment_int=$(($comment_count+0))
    echo $comment_int
}

findnewid() {
    if [[ $1 == "comment" ]] ; then 
        dir="comments"
        shift 1 
    else
        dir="tasks"
    fi
    if [[ -z $1 ]] ; then
        path="."
    else
        if ! [[ -d $(taskpath $1) ]] ; then 
            error="No such taskID"
        else
            path=$(taskpath $1)/$dir
        fi
    fi
    lastid=$(ls $path 2>/dev/null | grep "^[0-9]*$" | wc -l)
    newid=$(($lastid+1))
    if [[ -v error ]] ; then 
        echo $error
    else 
        echo $newid
    fi
}

newtaskpath() {
    newid=$(findnewid $1)
    if [[ $newid = "No such taskID" ]] ; then echo $newid ; exit 1 ; fi
    if [[ -z $1 ]] ; then 
        path=$(taskpath $1)
    else
        path=$(taskpath $1)/tasks 
    fi
    echo $path/$newid
}

newcommentpath() {
    newid=$(findnewid comment $1)
    if [[ $newid = "No such taskID" ]] ; then echo $newid ; exit 1 ; fi
    if [[ -z $1 ]] ; then 
        path=$(taskpath $1)
    else
        path=$(taskpath $1)/comments
    fi
    echo $path/$newid
}

main
