#!/usr/bin/env bash
# vim: set ts=4 sw=4 et:

source ./functions
pushd $(gettasksdir) >/dev/null

details=$1

if [[ -n "$details" ]] ; then
    if [[ "$details" = "done" ]] ; then
        echo TODO list completed tasks here
    	exit 1
    fi
    path=$(taskpath $details)
    if [[ -e $path/complete ]] ; then echo -n "DONE: " ; cat $path/task ; exit 0 ; fi
    if [[ -e $path/task ]] ; then cat $path/task ; fi 
    if [[ -d $path/comments ]] ; then cat $path/comments/* ; fi
else 
    for f in $(find . -name task | sort -n) ; do
        taskdir="$(dirname $f)"
        if [[ -e $taskdir/complete ]] ; then
            continue
        fi
        taskfile=$(taskid $f)
        comments=$(getcommentcount $f)
        echo -n "$taskfile: "
        if [[ $comments -ne 0 ]] ; then 
            echo -n "($comments) " 
        fi
	cat $f
    done
fi
